@extends('layouts.front')
@section('title', $product->name)
@section('content')
<section class="py-5 bg-light"><div class="container"><a href="{{ route('products',['category'=>$product->category->slug]) }}" class="text-decoration-none"><i class="fa fa-arrow-left me-1"></i> Back to {{ $product->category->name }}</a><div class="bg-white rounded-4 shadow-sm p-4 mt-3"><div class="row g-5">
  <div class="col-lg-5">@if($product->image)<img id="publicMainImage" class="main-product-image" src="{{ Storage::disk('public')->url($product->image) }}" alt="{{ $product->name }}">@else<div class="main-product-image d-flex align-items-center justify-content-center"><i class="fa fa-leaf fa-4x text-muted"></i></div>@endif @if($product->gallery_images)<div class="d-flex flex-wrap gap-2 mt-3">@foreach($product->gallery_images as $image)<img class="gallery-image" src="{{ Storage::disk('public')->url($image) }}" onclick="document.getElementById('publicMainImage').src=this.src" alt="">@endforeach</div>@endif</div>
  <div class="col-lg-7"><span class="badge bg-success">{{ $product->category->name }}</span><h1 class="fw-bold mt-3">{{ $product->name }}</h1>@if($product->brand)<p class="text-muted">Brand: {{ $product->brand }}</p>@endif<div class="detail-price">₹{{ number_format($product->retail_price,2) }} @if($product->mrp>$product->retail_price)<small class="text-muted text-decoration-line-through fs-6">MRP ₹{{ number_format($product->mrp,2) }}</small>@endif</div><p class="lead mt-3">{{ $product->short_description }}</p><div class="row g-3 border-top pt-3 mt-3"><div class="col-sm-6"><strong>HSN Code</strong><br>{{ $product->hsn_code ?: 'Not specified' }}</div><div class="col-sm-6"><strong>Refund Period</strong><br>{{ $product->refund_days ? $product->refund_days.' days' : 'Not available' }}</div></div>@auth<a class="btn btn-main mt-4" href="{{ route('catalog.show',$product) }}"><i class="fa fa-cart-shopping me-1"></i> Purchase from Wallet</a>@else<a class="btn btn-main mt-4" href="{{ route('login') }}">Login to Purchase</a>@endauth</div>
  @if($product->full_description)<div class="col-12 border-top pt-4"><h3>Product Description</h3><div class="text-muted" style="white-space:pre-line">{{ $product->full_description }}</div></div>@endif
</div></div>
@if($relatedProducts->isNotEmpty())<h3 class="fw-bold mt-5 mb-3">Related Products</h3><div class="row g-4">@foreach($relatedProducts as $related)<div class="col-sm-6 col-lg-3"><a class="text-decoration-none text-dark" href="{{ route('products.show',$related) }}"><div class="bg-white rounded-4 shadow-sm p-3 h-100">@if($related->image)<img class="w-100 rounded-3 mb-3" style="height:170px;object-fit:cover" src="{{ Storage::disk('public')->url($related->image) }}" alt="">@endif<h6 class="fw-bold">{{ $related->name }}</h6><strong class="text-success">₹{{ number_format($related->retail_price,2) }}</strong></div></a></div>@endforeach</div>@endif
</div></section>
@push('styles')<style>.main-product-image{width:100%;height:440px;object-fit:contain;background:#f3f6f4;border-radius:16px}.gallery-image{width:78px;height:78px;object-fit:cover;border-radius:9px;border:1px solid #ddd;cursor:pointer}.detail-price{font-size:32px;font-weight:900;color:#064719}</style>@endpush
@endsection
