@csrf
@if($product->exists) @method('PUT') @endif
<div class="row g-3">
  <div class="col-md-4"><label class="form-label">Seller</label><input class="form-control" name="seller" value="{{ old('seller',$product->seller) }}" placeholder="Seller name"></div>
  <div class="col-md-4"><label class="form-label">Category <span class="text-danger">*</span></label><select required class="form-select" name="category_id"><option value="">Select Category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$product->category_id)==$category->id)>{{ $category->parent ? $category->parent->name.' / ' : '' }}{{ $category->name }}</option>@endforeach</select></div>
  <div class="col-md-4"><label class="form-label">Brand</label><input class="form-control" name="brand" value="{{ old('brand',$product->brand) }}" placeholder="Brand name"></div>
  <div class="col-md-4"><label class="form-label">Name <span class="text-danger">*</span></label><input required class="form-control" id="name" name="name" value="{{ old('name',$product->name) }}" placeholder="Product name"></div>
  <div class="col-md-4"><label class="form-label">Slug <span class="text-danger">*</span></label><input required class="form-control" id="slug" name="slug" value="{{ old('slug',$product->slug) }}" placeholder="product-slug"></div>
  <div class="col-md-4"><label class="form-label">HSN Code</label><input class="form-control" name="hsn_code" value="{{ old('hsn_code',$product->hsn_code) }}"></div>
  <div class="col-md-4"><label class="form-label">Repurchase Distribution</label><input type="number" step="0.01" min="0" class="form-control" name="repurchase_distribution" value="{{ old('repurchase_distribution',$product->repurchase_distribution ?? 0) }}"></div>
  <div class="col-md-4"><label class="form-label">MRP <span class="text-danger">*</span></label><input required type="number" step="0.01" min="0" class="form-control" name="mrp" value="{{ old('mrp',$product->mrp) }}"></div>
  <div class="col-md-4"><label class="form-label">Retail Price <span class="text-danger">*</span></label><input required type="number" step="0.01" min="0" class="form-control" name="retail_price" value="{{ old('retail_price',$product->retail_price) }}"></div>
  <div class="col-md-4"><label class="form-label">Refund Days</label><input type="number" min="0" max="365" class="form-control" name="refund_days" value="{{ old('refund_days',$product->refund_days ?? 0) }}"></div>
  <div class="col-md-4"><label class="form-label">Main Image</label><input type="file" accept="image/*" class="form-control" name="image">@if($product->image)<small class="text-muted">Leave blank to keep current image.</small>@endif</div>
  <div class="col-md-4"><label class="form-label">Gallery Images</label><input type="file" accept="image/*" multiple class="form-control" name="gallery_images[]"><small class="text-muted">Up to 8 images.</small></div>
  <div class="col-md-4"><label class="form-label">Product Section</label><select class="form-select" name="product_section"><option value="">Choose...</option>@foreach(['Featured','Best Seller','New Arrival','Package Product'] as $section)<option @selected(old('product_section',$product->product_section)==$section)>{{ $section }}</option>@endforeach</select></div>
  <div class="col-md-4"><label class="form-label">Has Variants?</label><select class="form-select" name="has_variants"><option value="0" @selected(!old('has_variants',$product->has_variants))>No</option><option value="1" @selected(old('has_variants',$product->has_variants))>Yes</option></select></div>
  <div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="is_active"><option value="1" @selected(old('is_active',$product->is_active ?? true)==1)>Active</option><option value="0" @selected(old('is_active',$product->is_active ?? true)==0)>Inactive</option></select></div>
  <div class="col-12"><label class="form-label">Short Description</label><textarea rows="3" class="form-control" name="short_description">{{ old('short_description',$product->short_description) }}</textarea></div>
  <div class="col-12"><label class="form-label">Refund Description</label><textarea rows="3" class="form-control" name="refund_description">{{ old('refund_description',$product->refund_description) }}</textarea></div>
  <div class="col-12"><label class="form-label">Full Description</label><textarea rows="8" class="form-control" name="full_description">{{ old('full_description',$product->full_description) }}</textarea></div>
</div>
<button class="btn btn-main mt-4"><i class="fa fa-floppy-disk me-1"></i> {{ $product->exists ? 'Update Product' : 'Save Product' }}</button>
@push('scripts')<script>const n=document.getElementById('name'),s=document.getElementById('slug');let touched=s.value!=='';s.addEventListener('input',()=>touched=true);n.addEventListener('input',()=>{if(!touched)s.value=n.value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')});</script>@endpush
